import React,{Component} from 'react';
import { StyleSheet,} from 'react-native';
export default StyleSheet.create( {

    bgcontainer:{
      flex:1,
       alignSelf:"center",
        width:"100%",
        height:"100%",
      },
      Container: {
       alignSelf:"center",
        position:"absolute",
        width:"100%",
        top:"30%",
      },
      Container1: {
        alignSelf:"center",
         position:"absolute",
         width:"100%",
         bottom:"20%",
       },
      Input:{
      alignSelf:"center",
       color: '#0E061C',
        borderRadius:25,
        backgroundColor:'#F9FDF0',
        borderWidth:2,
        borderColor:'#0E061C',
        marginTop:"5%",
         padding:10,
        height:50,
        fontSize:20, 
       width:"90%",
      },
      btn:{
        marginTop:"17%",
        borderRadius:10,
        backgroundColor:'#0E061C',
        color:'#F9FDF0',
        borderWidth:2,
        borderColor:'#F9FDF0',
        height:50, 
      width:"100%",
      alignSelf: "center",
        position: 'absolute',
         bottom: 0,
      },
      btnRound:{
        alignSelf:"center",
             marginTop:"5%",
        borderRadius:50,
        backgroundColor:'#0E061C',
        color:'#F9FDF0',
        borderWidth:2,
        borderColor:'#F9FDF0',
        height:50,
        width:"90%",
             },
      text:{
        textAlign:"center",
           fontSize:25,        
           color:'#F9FDF0',    
      },
      btnContainer:{
        flex: 1,
        flexDirection:"row",
        alignItems: 'center',
        justifyContent: 'center',
       alignSelf: 'flex-end',
        position: 'absolute',
         bottom: 0,
      },
    btnT:{
     flex:1,
      backgroundColor:'#0E061C',
      borderWidth:2,
      borderColor:'#F9FDF0',
      justifyContent:"center",
      height:50,
      borderRadius:10,
    },
    btnS:{
      flex:1,
       backgroundColor:'#0E061C',
       justifyContent:"center",
       height:20,
       maxWidth:"20%",
       borderRadius:5,
       marginLeft:5,
     },
    BtnC1:{
     alignSelf:"flex-start",
           padding:10,
           paddingTop:15,
      borderRadius:50,
      color:'#F9FDF0',
      borderWidth:2,
      borderColor:'#F9FDF0',
      backgroundColor:"#0E061C",
      height:75,
      width:75,
       
    },
    BtnC2:{
      marginLeft:"58%",
               padding:10,
               paddingTop:15,
          borderRadius:50,
          color:'#F9FDF0',
          borderWidth:2,
          borderColor:'#F9FDF0',
          backgroundColor:"#0E061C",
          height:75,
          width:75,
           
        },
        BtnC:{
        marginLeft:"40%",
          borderRadius:50,
              color:'#F9FDF0',
              borderWidth:2,
              borderColor:'#F9FDF0',
              backgroundColor:"#0E061C",
              height:75,
              width:75,
               
            },

    btnCC:{
      flex: 1,
      flexDirection: 'row',
      alignSelf: 'center',
      position: 'absolute',
       bottom: "10%",
       width:"100%",

  } ,
  RVIEW:{
    alignSelf:"center",
    flexDirection:"row",
    borderRadius:25,
    backgroundColor:'#F9FDF0',
     marginTop:"5%",
     padding:5,
    height:50,
    fontSize:20,
    width:"90%",
  } ,
  REVIEW1:{
    flexDirection:"column",
width:"100%",
  },
  RVIEW2:{
    marginTop:1,
    height:20,
    color: '#0E061C',
    flexDirection:"row",
    width:"190%",
  },
  Input2:{
    color: '#0E061C',
     fontSize:20, 
  maxWidth:"60%",
  },

text2:{
  paddingLeft:3,
  paddingTop:5,
  paddingBottom:5,
  alignSelf:"center",
  textAlign:"center",
  fontSize:15,        
  color:"#0E061C",
},
text3:{
  paddingLeft:10,
  textAlign:"center",
  fontSize:15,        
  color:"#0E061C",
},
  text4:{
    textAlign:"center",
  fontSize:15,        
  color:"#F9FDF0",
},
image:{
  marginLeft:10,
width:20,
height:20,

}}

    );


